<?php

/*
save output to HTML-wrappers.php

makes a function for each HTML5 tag, like this:
function tag( $atts = '', $contents = '' )
where name conflicts with built-in function, add _ to name:
function tag_( $atts = '', $contents = '' )

$contents can be an array
*/

//define( 'ELEMENT_NL', '"\\n"' );
define( 'ELEMENT_NL', '""' );

/////////////////////////////////////////////////////
// HTML5 elements from w3c

$HTML5_ELEMENTS = 
//element	start tag	end tag	add _
'a				required		required	no
abbr			required		required	no
address		required		required	no
area			required		empty		no
article		required		required	no
aside			required		required	no
audio			required		required	no
b				required		required	no
base			required		empty		no
bb				required		required	no
bdo			required		required	no
blockquote	required		required	no
body			optional		optional	no
br				required		empty		no
button		required		required	no
canvas		required		required	no
caption		required		required	no
cite			required		required	no
code			required		required	no
col			required		empty		no
colgroup		required		optional	no
command		required		empty		no
datagrid		required		required	no
datalist		required		required	no
dd				required		optional	no
del			required		required	no
details		required		required	no
dfn			required		required	no
dialog		required		required	no
div			required		required	no
dl				required		required	no
dt				required		optional	no
em				required		required	no
embed			required		empty		no
fieldset		required		required	no
figure		required		required	no
footer		required		required	no
form			required		required	no
h1				required		required	no
h2				required		required	no
h3				required		required	no
h4				required		required	no
h5				required		required	no
h6				required		required	no
head			optional		optional	no
header		required		required	no
hgroup		required		required	no
hr				required		empty		no
html			optional		optional	no
i				required		required	no
iframe		required		required	no
img			required		empty		no
input			required		empty		no
ins			required		required	no
kbd			required		required	no
label			required		required	no
legend		required		required	no
li				required		optional	no
link			required		empty		no
map			required		required	no
mark			required		required	no
menu			required		required	no
meta			required		empty		no
meter			required		required	no
nav			required		required	no
noscript		required		required	no
object		required		required	no
ol				required		required	no
optgroup		required		optional	no
option		required		optional	no
output		required		required	no
p				required		optional	no
param			required		empty		no
pre			required		required	no
progress		required		required	no
q				required		required	no
rp				required		required	no
rt				required		required	no
ruby			required		required	no
samp			required		required	no
script		required		required	no
section		required		required	no
select		required		required	no
small			required		required	no
source		required		empty		no
span			required		required	no
strong		required		required	no
style			required		required	no
sub			required		required	no
sup			required		required	no
table			required		required	no
tbody			optional		optional	no
td				required		optional	no
textarea		required		required	no
tfoot			optional		optional	no
th				required		optional	no
thead			optional		optional	no
time			required		required	no
title			required		required	no
tr				required		optional	no
ul				required		required	no
var			required		required	yes
video			required		required	no'
;


print "<?php\n\n// Do Not Edit This File. Edit " . __FILE__ . " Instead.\n\n";

////////////////////
// create import statement

$list = '';
foreach (explode( "\n",  $HTML5_ELEMENTS ) as $line)
{
	list( $element, $start_tag, $end_tag, $addUnderscore ) = preg_split( "/\t+/",  $line );

	$funcName = $element;

	if (
		function_exists( $element ) or
		$addUnderscore == 'yes'
	)
	{
		$funcName .= '_';
	}

  $list .= "$funcName,";
}

$list = preg_replace( "/,$/", '', $list );

print "// paste the following if you want to:\n// use function WebSight\\{" . $list . "};\n\n";


print
'

namespace WebSight;

function element( $name, $atts = \'\', $contents = \'\', $end_tag = true )
{
	if (is_array( $contents ))
	{
		$e = \'\';
		foreach ($contents as $c)
		{
			$e .= element( $name, $atts, $c, $end_tag );
		}
		return $e;
	}

	if ($atts) {
		$atts = " $atts";
	}

	if ($contents) {
		$contents = ' . ELEMENT_NL . ' . $contents . ' . ELEMENT_NL . ';
	}

	return "<$name$atts>" . $contents . ($end_tag ? "</$name>" : "") . ' . ELEMENT_NL . ';
}


';

foreach (explode( "\n",  $HTML5_ELEMENTS ) as $line)
{
	list( $element, $start_tag, $end_tag, $addUnderscore ) = preg_split( "/\t+/",  $line );

	$funcName = $element;

	if (
		function_exists( $element ) or
		$addUnderscore == 'yes'
	)
	{
		$funcName .= '_';
	}

	if ($end_tag == 'required' or $end_tag == 'optional')
	{
		$end_tag = 'true';
	}
	else
	{
		$end_tag = 'false';
	}

	print
"
function $funcName( \$atts = '', \$contents = '' )
{
	return element( 
		'$element', 
		\$atts, 
		\$contents, 
		$end_tag
	);
}

";
}


