<?php

// Do Not Edit This File. Edit /home/ec2-user/WebSight/generate-HTML-wrappers-atts-first.php Instead.

// paste the following if you want to:
// use function WebSight\{a,abbr,address,area,article,aside,audio,b,base,bb,bdo,blockquote,body,br,button,canvas,caption,cite,code,col,colgroup,command,datagrid,datalist,dd,del,details,dfn,dialog,div,dl_,dt,em,embed,fieldset,figure,footer,form,h1,h2,h3,h4,h5,h6,head,header_,hgroup,hr,html,i,iframe,img,input,ins,kbd,label,legend,li,link_,map,mark,menu,meta,meter,nav,noscript,object,ol,optgroup,option,output,p,param,pre,progress,q,rp,rt,ruby,samp,script,section,select,small,source,span,strong,style,sub,sup,table,tbody,td,textarea,tfoot,th,thead,time_,title,tr,ul,var_,video};



namespace WebSight;

function element( $name, $atts = '', $contents = '', $end_tag = true )
{
	if (is_array( $contents ))
	{
		$e = '';
		foreach ($contents as $c)
		{
			$e .= element( $name, $atts, $c, $end_tag );
		}
		return $e;
	}

	if ($atts) {
		$atts = " $atts";
	}

	if ($contents) {
		$contents = "" . $contents . "";
	}

	return "<$name$atts>" . $contents . ($end_tag ? "</$name>" : "") . "";
}



function a( $atts = '', $contents = '' )
{
	return element( 
		'a', 
		$atts, 
		$contents, 
		true
	);
}


function abbr( $atts = '', $contents = '' )
{
	return element( 
		'abbr', 
		$atts, 
		$contents, 
		true
	);
}


function address( $atts = '', $contents = '' )
{
	return element( 
		'address', 
		$atts, 
		$contents, 
		true
	);
}


function area( $atts = '', $contents = '' )
{
	return element( 
		'area', 
		$atts, 
		$contents, 
		false
	);
}


function article( $atts = '', $contents = '' )
{
	return element( 
		'article', 
		$atts, 
		$contents, 
		true
	);
}


function aside( $atts = '', $contents = '' )
{
	return element( 
		'aside', 
		$atts, 
		$contents, 
		true
	);
}


function audio( $atts = '', $contents = '' )
{
	return element( 
		'audio', 
		$atts, 
		$contents, 
		true
	);
}


function b( $atts = '', $contents = '' )
{
	return element( 
		'b', 
		$atts, 
		$contents, 
		true
	);
}


function base( $atts = '', $contents = '' )
{
	return element( 
		'base', 
		$atts, 
		$contents, 
		false
	);
}


function bb( $atts = '', $contents = '' )
{
	return element( 
		'bb', 
		$atts, 
		$contents, 
		true
	);
}


function bdo( $atts = '', $contents = '' )
{
	return element( 
		'bdo', 
		$atts, 
		$contents, 
		true
	);
}


function blockquote( $atts = '', $contents = '' )
{
	return element( 
		'blockquote', 
		$atts, 
		$contents, 
		true
	);
}


function body( $atts = '', $contents = '' )
{
	return element( 
		'body', 
		$atts, 
		$contents, 
		true
	);
}


function br( $atts = '', $contents = '' )
{
	return element( 
		'br', 
		$atts, 
		$contents, 
		false
	);
}


function button( $atts = '', $contents = '' )
{
	return element( 
		'button', 
		$atts, 
		$contents, 
		true
	);
}


function canvas( $atts = '', $contents = '' )
{
	return element( 
		'canvas', 
		$atts, 
		$contents, 
		true
	);
}


function caption( $atts = '', $contents = '' )
{
	return element( 
		'caption', 
		$atts, 
		$contents, 
		true
	);
}


function cite( $atts = '', $contents = '' )
{
	return element( 
		'cite', 
		$atts, 
		$contents, 
		true
	);
}


function code( $atts = '', $contents = '' )
{
	return element( 
		'code', 
		$atts, 
		$contents, 
		true
	);
}


function col( $atts = '', $contents = '' )
{
	return element( 
		'col', 
		$atts, 
		$contents, 
		false
	);
}


function colgroup( $atts = '', $contents = '' )
{
	return element( 
		'colgroup', 
		$atts, 
		$contents, 
		true
	);
}


function command( $atts = '', $contents = '' )
{
	return element( 
		'command', 
		$atts, 
		$contents, 
		false
	);
}


function datagrid( $atts = '', $contents = '' )
{
	return element( 
		'datagrid', 
		$atts, 
		$contents, 
		true
	);
}


function datalist( $atts = '', $contents = '' )
{
	return element( 
		'datalist', 
		$atts, 
		$contents, 
		true
	);
}


function dd( $atts = '', $contents = '' )
{
	return element( 
		'dd', 
		$atts, 
		$contents, 
		true
	);
}


function del( $atts = '', $contents = '' )
{
	return element( 
		'del', 
		$atts, 
		$contents, 
		true
	);
}


function details( $atts = '', $contents = '' )
{
	return element( 
		'details', 
		$atts, 
		$contents, 
		true
	);
}


function dfn( $atts = '', $contents = '' )
{
	return element( 
		'dfn', 
		$atts, 
		$contents, 
		true
	);
}


function dialog( $atts = '', $contents = '' )
{
	return element( 
		'dialog', 
		$atts, 
		$contents, 
		true
	);
}


function div( $atts = '', $contents = '' )
{
	return element( 
		'div', 
		$atts, 
		$contents, 
		true
	);
}


function dl_( $atts = '', $contents = '' )
{
	return element( 
		'dl', 
		$atts, 
		$contents, 
		true
	);
}


function dt( $atts = '', $contents = '' )
{
	return element( 
		'dt', 
		$atts, 
		$contents, 
		true
	);
}


function em( $atts = '', $contents = '' )
{
	return element( 
		'em', 
		$atts, 
		$contents, 
		true
	);
}


function embed( $atts = '', $contents = '' )
{
	return element( 
		'embed', 
		$atts, 
		$contents, 
		false
	);
}


function fieldset( $atts = '', $contents = '' )
{
	return element( 
		'fieldset', 
		$atts, 
		$contents, 
		true
	);
}


function figure( $atts = '', $contents = '' )
{
	return element( 
		'figure', 
		$atts, 
		$contents, 
		true
	);
}


function footer( $atts = '', $contents = '' )
{
	return element( 
		'footer', 
		$atts, 
		$contents, 
		true
	);
}


function form( $atts = '', $contents = '' )
{
	return element( 
		'form', 
		$atts, 
		$contents, 
		true
	);
}


function h1( $atts = '', $contents = '' )
{
	return element( 
		'h1', 
		$atts, 
		$contents, 
		true
	);
}


function h2( $atts = '', $contents = '' )
{
	return element( 
		'h2', 
		$atts, 
		$contents, 
		true
	);
}


function h3( $atts = '', $contents = '' )
{
	return element( 
		'h3', 
		$atts, 
		$contents, 
		true
	);
}


function h4( $atts = '', $contents = '' )
{
	return element( 
		'h4', 
		$atts, 
		$contents, 
		true
	);
}


function h5( $atts = '', $contents = '' )
{
	return element( 
		'h5', 
		$atts, 
		$contents, 
		true
	);
}


function h6( $atts = '', $contents = '' )
{
	return element( 
		'h6', 
		$atts, 
		$contents, 
		true
	);
}


function head( $atts = '', $contents = '' )
{
	return element( 
		'head', 
		$atts, 
		$contents, 
		true
	);
}


function header_( $atts = '', $contents = '' )
{
	return element( 
		'header', 
		$atts, 
		$contents, 
		true
	);
}


function hgroup( $atts = '', $contents = '' )
{
	return element( 
		'hgroup', 
		$atts, 
		$contents, 
		true
	);
}


function hr( $atts = '', $contents = '' )
{
	return element( 
		'hr', 
		$atts, 
		$contents, 
		false
	);
}


function html( $atts = '', $contents = '' )
{
	return element( 
		'html', 
		$atts, 
		$contents, 
		true
	);
}


function i( $atts = '', $contents = '' )
{
	return element( 
		'i', 
		$atts, 
		$contents, 
		true
	);
}


function iframe( $atts = '', $contents = '' )
{
	return element( 
		'iframe', 
		$atts, 
		$contents, 
		true
	);
}


function img( $atts = '', $contents = '' )
{
	return element( 
		'img', 
		$atts, 
		$contents, 
		false
	);
}


function input( $atts = '', $contents = '' )
{
	return element( 
		'input', 
		$atts, 
		$contents, 
		false
	);
}


function ins( $atts = '', $contents = '' )
{
	return element( 
		'ins', 
		$atts, 
		$contents, 
		true
	);
}


function kbd( $atts = '', $contents = '' )
{
	return element( 
		'kbd', 
		$atts, 
		$contents, 
		true
	);
}


function label( $atts = '', $contents = '' )
{
	return element( 
		'label', 
		$atts, 
		$contents, 
		true
	);
}


function legend( $atts = '', $contents = '' )
{
	return element( 
		'legend', 
		$atts, 
		$contents, 
		true
	);
}


function li( $atts = '', $contents = '' )
{
	return element( 
		'li', 
		$atts, 
		$contents, 
		true
	);
}


function link_( $atts = '', $contents = '' )
{
	return element( 
		'link', 
		$atts, 
		$contents, 
		false
	);
}


function map( $atts = '', $contents = '' )
{
	return element( 
		'map', 
		$atts, 
		$contents, 
		true
	);
}


function mark( $atts = '', $contents = '' )
{
	return element( 
		'mark', 
		$atts, 
		$contents, 
		true
	);
}


function menu( $atts = '', $contents = '' )
{
	return element( 
		'menu', 
		$atts, 
		$contents, 
		true
	);
}


function meta( $atts = '', $contents = '' )
{
	return element( 
		'meta', 
		$atts, 
		$contents, 
		false
	);
}


function meter( $atts = '', $contents = '' )
{
	return element( 
		'meter', 
		$atts, 
		$contents, 
		true
	);
}


function nav( $atts = '', $contents = '' )
{
	return element( 
		'nav', 
		$atts, 
		$contents, 
		true
	);
}


function noscript( $atts = '', $contents = '' )
{
	return element( 
		'noscript', 
		$atts, 
		$contents, 
		true
	);
}


function object( $atts = '', $contents = '' )
{
	return element( 
		'object', 
		$atts, 
		$contents, 
		true
	);
}


function ol( $atts = '', $contents = '' )
{
	return element( 
		'ol', 
		$atts, 
		$contents, 
		true
	);
}


function optgroup( $atts = '', $contents = '' )
{
	return element( 
		'optgroup', 
		$atts, 
		$contents, 
		true
	);
}


function option( $atts = '', $contents = '' )
{
	return element( 
		'option', 
		$atts, 
		$contents, 
		true
	);
}


function output( $atts = '', $contents = '' )
{
	return element( 
		'output', 
		$atts, 
		$contents, 
		true
	);
}


function p( $atts = '', $contents = '' )
{
	return element( 
		'p', 
		$atts, 
		$contents, 
		true
	);
}


function param( $atts = '', $contents = '' )
{
	return element( 
		'param', 
		$atts, 
		$contents, 
		false
	);
}


function pre( $atts = '', $contents = '' )
{
	return element( 
		'pre', 
		$atts, 
		$contents, 
		true
	);
}


function progress( $atts = '', $contents = '' )
{
	return element( 
		'progress', 
		$atts, 
		$contents, 
		true
	);
}


function q( $atts = '', $contents = '' )
{
	return element( 
		'q', 
		$atts, 
		$contents, 
		true
	);
}


function rp( $atts = '', $contents = '' )
{
	return element( 
		'rp', 
		$atts, 
		$contents, 
		true
	);
}


function rt( $atts = '', $contents = '' )
{
	return element( 
		'rt', 
		$atts, 
		$contents, 
		true
	);
}


function ruby( $atts = '', $contents = '' )
{
	return element( 
		'ruby', 
		$atts, 
		$contents, 
		true
	);
}


function samp( $atts = '', $contents = '' )
{
	return element( 
		'samp', 
		$atts, 
		$contents, 
		true
	);
}


function script( $atts = '', $contents = '' )
{
	return element( 
		'script', 
		$atts, 
		$contents, 
		true
	);
}


function section( $atts = '', $contents = '' )
{
	return element( 
		'section', 
		$atts, 
		$contents, 
		true
	);
}


function select( $atts = '', $contents = '' )
{
	return element( 
		'select', 
		$atts, 
		$contents, 
		true
	);
}


function small( $atts = '', $contents = '' )
{
	return element( 
		'small', 
		$atts, 
		$contents, 
		true
	);
}


function source( $atts = '', $contents = '' )
{
	return element( 
		'source', 
		$atts, 
		$contents, 
		false
	);
}


function span( $atts = '', $contents = '' )
{
	return element( 
		'span', 
		$atts, 
		$contents, 
		true
	);
}


function strong( $atts = '', $contents = '' )
{
	return element( 
		'strong', 
		$atts, 
		$contents, 
		true
	);
}


function style( $atts = '', $contents = '' )
{
	return element( 
		'style', 
		$atts, 
		$contents, 
		true
	);
}


function sub( $atts = '', $contents = '' )
{
	return element( 
		'sub', 
		$atts, 
		$contents, 
		true
	);
}


function sup( $atts = '', $contents = '' )
{
	return element( 
		'sup', 
		$atts, 
		$contents, 
		true
	);
}


function table( $atts = '', $contents = '' )
{
	return element( 
		'table', 
		$atts, 
		$contents, 
		true
	);
}


function tbody( $atts = '', $contents = '' )
{
	return element( 
		'tbody', 
		$atts, 
		$contents, 
		true
	);
}


function td( $atts = '', $contents = '' )
{
	return element( 
		'td', 
		$atts, 
		$contents, 
		true
	);
}


function textarea( $atts = '', $contents = '' )
{
	return element( 
		'textarea', 
		$atts, 
		$contents, 
		true
	);
}


function tfoot( $atts = '', $contents = '' )
{
	return element( 
		'tfoot', 
		$atts, 
		$contents, 
		true
	);
}


function th( $atts = '', $contents = '' )
{
	return element( 
		'th', 
		$atts, 
		$contents, 
		true
	);
}


function thead( $atts = '', $contents = '' )
{
	return element( 
		'thead', 
		$atts, 
		$contents, 
		true
	);
}


function time_( $atts = '', $contents = '' )
{
	return element( 
		'time', 
		$atts, 
		$contents, 
		true
	);
}


function title( $atts = '', $contents = '' )
{
	return element( 
		'title', 
		$atts, 
		$contents, 
		true
	);
}


function tr( $atts = '', $contents = '' )
{
	return element( 
		'tr', 
		$atts, 
		$contents, 
		true
	);
}


function ul( $atts = '', $contents = '' )
{
	return element( 
		'ul', 
		$atts, 
		$contents, 
		true
	);
}


function var_( $atts = '', $contents = '' )
{
	return element( 
		'var', 
		$atts, 
		$contents, 
		true
	);
}


function video( $atts = '', $contents = '' )
{
	return element( 
		'video', 
		$atts, 
		$contents, 
		true
	);
}

